### ISSUE TITLE
cloning to Rob's local stand alone

### ISSUE THREAD

**Issue by banillie** [banillie/projectlibrary#3]
@hammerheadlemon

on attempting to install requirement.txt into the .venv for Rob, received the following. 

`  Could not find a version that satisfies the requirement bcompiler-engine@ https://github.com/hammerheadlemon/bcompiler-engine/archive/master.zip#egg=bcompiler-engine (from datamaps->-r re
quirements.txt (line 1)) (from versions: )

No matching distribution found for bcompiler-engine@ https://github.com/hammerheadlemon/bcompiler-engine/archive/master.zip#egg=bcompiler-engine (from datamaps->-r requirements.txt (line 1)) `

**Comment by yulqen** [comment]
So, this is when trying to `pip install -r requirements.txt` for `analysis_engine`, rather than `projectlibrary`, yes? I didn't think Rob or Joe needed to manually install `projectlibrary`. Correct me if I'm wrong.

The most obvious problem here is that the machine didn't have a working internet connection. Were you able to check that??

**Comment by banillie** [comment]
Ok will check later. Thanks. 

And... yes to your first question. Sorry should have put it there.

**Comment by banillie** [comment]
@hammerheadlemon Sorted. It was because pip needed to be updated!

**Comment by yulqen** [comment]
Oh yeah - ok. Good to know that's the outcome when using an old pip.
